### ISSUE TITLE
Лицензия для DLE + XenForo (License)

### ISSUE THREAD

**Issue by PanasPanasovich** [dautushenka/dle-xenforo#1]
Приветствую, после установки, в DLE на главной теперь висит сообщение: 

> Вы используете не лицензионную версию модуля DLE + XenForo.
> За информацией обращайтесь на форум http://forum.kaliostro.net/
> You are not using licensed version of the module DLE + XenForo.
> For information, visit the forum http://forum.kaliostro.net/

Что ещё требуется?

**Comment by dautushenka** [comment]
Спасибо, обновитесь с репозитория, я убрал старый код проверки лицензии.
