### ISSUE TITLE
Ошибка при массовом создании пользователей в XenForo

### ISSUE THREAD

**Issue by Erriour** [dautushenka/dle-xenforo#2]
Привет. Хочу перегнать пользователей из DLE в XenForo (около 500000 аккаунтов).

Написал небольшой скрипт, в котором шаги разбиваются на 5000 акков за раз.
`for($i = $start_ids; $i<=$finish_ids; $i++){`
     ` if($i == 1) continue;`
     `$user = getUserInfoById($i);`
     ` if(empty($user)) continue;`
     ` XenIntegration::getInstance()->createMember(stripslashes($user['name']), md5(randomPassword()), $user['email']);`
       ` }`

При запуске получаю ошибку:
Fatal error: Cannot redeclare mergeWithDefault() (previously declared in /home/site/engine/modules/XenIntegration/XenIntegration.php:483) in /home/site/engine/modules/XenIntegration/XenIntegration.php on line 483

Я понимаю о чём ошибка, но почему оно пытается повторно объявить функцию, ссылаясь на ту же функцию, если она всего одна?

**Comment by dautushenka** [comment]
@Erriour Скорее всего файл в котором объявлена функцрия подключен (include или require) 2 раза и при повторном подключение получаем ошибку, 2 варианта решения:
1. Искать где и как подключается файл в котором обьявлена данная функция
2. Обернуть функци в условие` if (!function_exists('mergeWithDefault'))`

**Comment by Erriour** [comment]
Я всё подключаю через require_once, повторяться файл точно не должен (да и не повторяется).

Я так подозреваю, что это из-за того, что тут в коде интеграции функция в функции. И когда я вызываю функцию в цикле, та функция создаётся каждый раз...

Второй вариант помог. Спасибо!
