### ISSUE TITLE
DLE 13.0 и XenForo 2.1.5

### ISSUE THREAD

**Issue by CounterPill** [dautushenka/dle-xenforo#3]
Как быть с новыми версиями движков? Понятное дело многое уже изменили, но возможно ли поковырять старый мост для работы с новыми версиями? 
Я попробую, но с XenForo никогда еще не работал.

**Comment by dautushenka** [comment]
@CounterPill К сожалению я уже давно не работаю не с DLE не с этим форумом, на сколько я помню у XenForo была неплохая система хуков и модулей, не думаю что она могла сильно поменяться, надеюсь вам будет просто разобраться. Также можете взглянуть на форки, возможно кто-то уже реализовал поддержку новых версий
