### ISSUE TITLE
Обновление для Xenforo 2

### ISSUE THREAD

**Issue by RuKzEn** [dautushenka/dle-xenforo#4]
Извините пожалуйста за наглость. 
Можете обновить это чудесное изобретение до последних версий CSM.
На данный в Xenforo 2 нет возможности установить плагины (дополнения, аддоны) из первый линейки форума (файлы в плагины с расширением .xml CSM xenforo не принимает. Только .zip).

Так же во второй версии нет файла library/config.php
он находится в src/config.php
То есть на данный момент пункт Установка интеграции на форум выполнить нельзя.

Я могу заплатить если нужно (не много) Но для стимула

**Comment by dautushenka** [comment]
Доброе время суток, я бы с радостью Вам помог, но уже с тех пор я не работаю с этими CMS системами и не курсе что и как там поменялось, проанализируйте форки, возможно кто-то уже это реализовал.
Извините пока помочь не могу.
